import type { CaseFile } from './contracts';
const archiveTime = '2026-08-19T00:00:00.000Z';
const archive = { sourceType: 'ARCHIVE' as const, sourceUrl: 'file:///reports/alpha-witness-yan-novikov-pocket-option.md', retrievedAt: archiveTime, title: 'ALPHA WITNESS — Evidence Case AW-26-0819-A7F3', note: 'Imported from supplied archived report; not live-generated.' };
const claims = [
  ['~00:32', 'The creator plans about ten trades of $100, including OTC pairs.', 'Specific, but far too small a sample.'],
  ['~01:04–01:20', 'He hypothesizes that continued AI learning could improve performance from about 50% to 60% after a year.', 'Model, training process, payout and evidence are NON AVAILABLE.'],
  ['~03:12', 'He says at least 1,000–2,000 trades are needed before drawing conclusions.', 'This directly undermines conclusions from the short session.'],
  ['~09:35', 'He reports approximately +$150 without recovery trades.', 'Not independently reproducible from a complete ledger.']
].map(([time, statement, caveat], i) => ({ id: `archived-claim-${i + 1}`, statement: `${time} — ${statement}`, status: 'OBSERVED' as const, availability: 'AVAILABLE' as const, quotations: [statement], evidenceIds: ['archived-source'], provenance: [archive], caveat }));
export const archivedCase: CaseFile = { id: 'AW-26-0819-A7F3', createdAt: archiveTime, updatedAt: archiveTime, input: { kind: 'url', label: 'AI Trading on Pocket Option / Does It Work or NOT?' }, classification: 'VIDEO', status: 'COMPLETE', title: 'AI Trading on Pocket Option / Does It Work or NOT?', shareable: true, archived: true, evidenceLedger: [{ id: 'archived-source', kind: 'SOURCE', title: 'Supplied report: Yan Novikov / Pocket Option', content: 'Primary source: “AI Trading on Pocket Option / Does It Work or NOT? Professional Opinion / Binary Options 2024”. The report records a preliminary product test, not an audited strategy or verified track record. Complete trade ledger, payout, drawdown and independent reconstruction are NON AVAILABLE.', availability: 'AVAILABLE', provenance: archive }], claims, verdict: { decision: 'VETO', rationale: 'INSUFFICIENT EVIDENCE. No trade and no paper test derived from this claim.', availability: 'AVAILABLE', gates: [{ name: 'Independent, reproducible source evidence', passed: true, detail: 'Archived report identifies a primary video and contextual sources.' }, { name: 'Complete ledger / market validation', passed: false, detail: 'Complete transaction ledger and independent price feed are NON AVAILABLE.' }, { name: 'Independent out-of-sample test', passed: false, detail: 'No reproducible out-of-sample test is supplied.' }, { name: 'Automatic paper-test authorization', passed: false, detail: 'Disabled; verdict remains VETO.' }] }, notebook: { overview: 'Evidence reliability: 20/100; low data confidence. Trader overall reliability is NON AVAILABLE—one video cannot establish person-level reputation.', method: 'Archived report review with source claims, statistical audit, independent-source comparison and conservative Risk Guardian gates.', openQuestions: ['Can 1,000+ exportable trades be independently verified?', 'What are the exact contract payouts and drawdowns?', 'Is the commercial relationship with the broker disclosed?'] } };
