import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getCaseRepository } from '@/lib/repositoryFactory';
import { isPublicGuestCase } from '@/lib/repository';
import type { CaseFile } from '@/lib/contracts';

function statusClass(status: string) { return `status status-${status.toLowerCase()}`; }
export default async function CasePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let item: CaseFile | null = null;
  if (id === 'archived-yan-novikov') { const { archivedCase } = await import('@/lib/sampleCase'); item = archivedCase; }
  else { try { const found = await (await getCaseRepository()).get(id); item = isPublicGuestCase(found) ? found : null; } catch { item = null; } }
  if (!item) notFound();
  const evidenceAvailable = item.evidenceLedger.filter((e) => e.availability === 'AVAILABLE').length;
  return <section className="case-shell"><div className="case-head"><div><div className="eyebrow">CASE FILE / {item.id}</div><h1>{item.title}</h1><p className="case-input">INPUT · {item.input.kind.toUpperCase()} · {item.archived ? 'VERIFIED ARCHIVED CASE' : 'GUEST CASE'}</p></div><div className={statusClass(item.status)}>{item.status}</div></div>{item.archived && <div className="archive-banner">VERIFIED ARCHIVED CASE <span>Imported from the supplied report. This record is not live-generated.</span></div>}{!item.archived && <div className="archive-banner">PUBLIC GUEST CASE <span>This case is read-only and shareable by anyone with its link. Private notes are disabled until owner authentication exists.</span></div>}<div className="ruling"><div className="eyebrow">RISK GUARDIAN / FINAL RULING</div><div className={`verdict verdict-${item.verdict.decision.toLowerCase()}`}>{item.verdict.decision}</div><p>{item.verdict.rationale}</p></div><div className="case-meta"><div><small>CLASSIFICATION</small><strong>{item.classification}</strong></div><div><small>EVIDENCE ITEMS</small><strong>{evidenceAvailable} / {item.evidenceLedger.length} AVAILABLE</strong></div><div><small>CLAIMS</small><strong>{item.claims.length ? item.claims.length : 'NON AVAILABLE'}</strong></div><div><small>ANALYSIS</small><strong>{item.verdict.availability}</strong></div></div><div className="case-grid"><div><div className="section-label">EVIDENCE LEDGER</div>{item.evidenceLedger.map((e) => <article className="evidence-card" key={e.id}><div className="card-top"><span>{e.kind}</span><span>{e.availability}</span></div><h3>{e.title}</h3><p>{e.content || 'No extract available.'}</p><small>{e.provenance.sourceType} · {e.provenance.sourceUrl || 'guest input'} · {e.provenance.retrievedAt}</small></article>)}</div><aside><div className="section-label">NOTEBOOK</div><article className="notebook"><h3>OVERVIEW</h3><p>{item.notebook.overview}</p><h3>METHOD</h3><p>{item.notebook.method}</p><h3>OPEN QUESTIONS</h3><ul>{item.notebook.openQuestions.map((q) => <li key={q}>{q}</li>)}</ul></article><div className="section-label">GATES</div><article className="notebook">{item.verdict.gates.map((gate) => <p className="gate" key={gate.name}><b>{gate.passed ? 'PASS' : 'HOLD'}</b> {gate.name}<br /><small>{gate.detail}</small></p>)}</article></aside></div><div className="claims"><div className="section-label">CLAIM LEDGER</div>{item.claims.length ? item.claims.map((claim) => <article className="claim" key={claim.id}><span>{claim.status}</span><h3>{claim.statement}</h3>{claim.quotations.map((quote) => <blockquote key={quote}>“{quote}”</blockquote>)}</article>) : <div className="empty-state">{item.verdict.availability}<br /><small>No synthetic claims were created. Configure an approved analysis provider to request quoted analysis.</small></div>}</div><Link href="/" className="outline-button">← OPEN ANOTHER CASE</Link></section>;
}
