'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function CaseForm() {
  const router = useRouter(); const [mode, setMode] = useState('url'); const [value, setValue] = useState(''); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { let response: Response; if (mode === 'pdf') { const form = new FormData(); if (file) form.append('file', file); response = await fetch('/api/cases', { method: 'POST', body: form }); } else { response = await fetch('/api/cases', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind: mode, value }) }); } const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Request failed'); router.push(`/cases/${body.id}`); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); setBusy(false); } }
  return <form onSubmit={submit} className="intake-form"><div className="mode-tabs">{[['url','PUBLIC URL'],['text','PASTE TEXT'],['name','TRADER / PERSON'],['ticker','ASSET TICKER'],['pdf','PDF UPLOAD']].map(([key,label]) => <button type="button" key={key} className={mode === key ? 'active' : ''} onClick={() => { setMode(key); setValue(''); setFile(null); }}>{label}</button>)}</div><label className="sr-only" htmlFor="intake">Universal input</label>{mode === 'pdf' ? <label className="dropzone"><input id="intake" type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] || null)} /> <strong>{file ? file.name : 'DROP A PDF OR CHOOSE FILE'}</strong><span>PDF · max 2 MB · metadata and hash only · text extraction is unavailable</span></label> : <textarea id="intake" value={value} onChange={(e) => setValue(e.target.value)} required placeholder={mode === 'url' ? 'https://…' : mode === 'ticker' ? 'BTC / AAPL / SPY' : mode === 'name' ? 'Name or public profile' : 'Paste source text. Claims will never be invented.'} rows={5} />}{error && <p className="form-error">{error}</p>}<button className="submit" disabled={busy || (mode === 'pdf' ? !file : !value.trim())}>{busy ? 'OPENING CASE…' : 'OPEN CASE ↗'}</button><p className="microcopy"><strong>Public guest case:</strong> anyone with the unguessable case link can read the evidence. Do not submit confidential, personal, or proprietary text. Guest cases are read-only; private notes are disabled.</p></form>;
}
